project_id = "tkjiovnlqwmpikejtanu"

[functions.send-notification-email]
verify_jwt = false

[functions.get-user-emails]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = false

[functions.process-notification-queue]
verify_jwt = false

[functions.get-vapid-key]
verify_jwt = false